---


- name: Ensure the necessary config directories are present on the host
  file:
    state: directory
    path: "{{ item }}"
    mode: "0777"
  when: item is defined
  with_items:
    - "{{ mosquitto_root_directory }}"
    - "{{ mosquitto_data_directory }}"
    - "{{ mosquitto_log_directory }}"
  tags:
    - mqtt
    - config

- name: Ensure configuration file is present
  template:
    src: mosquitto.conf.j2
    dest: "{{ mosquitto_root_directory }}/mosquitto.conf"
  tags:
    - mqtt
    - config

- import_tasks: _var_change_detection.yml
  vars:
    _change_detection_var_name: "mosquitto_users"
    _change_detection_var: "{{ mosquitto_users }}"
  tags:
    - mqtt
    - auth

- name: Delete the existing password file
  file:
    path: "{{ mosquitto_passwd_file}}"
    state: absent
  when: _change_detection_was_detected
  tags:
    - mqtt
    - auth

- name: Start with an empty password file
  file: path="/etc/mosquitto/passwd" state=touch
  when: _change_detection_was_detected
  tags:
    - mqtt
    - auth

- name: Write the temporary password file contents
  command: "docker run --rm -v /etc/mosquitto/passwd:/mosquitto/config/passwd \
    eclipse-mosquitto:{{ mosquitto_docker_version }} mosquitto_passwd \
    -b /mosquitto/config/passwd {{ item.name }} {{ item.password }}"
  with_items: "{{ mosquitto_users }}"
  no_log: true
  when: _change_detection_was_detected
  notify: restart mosquitto
  tags:
    - mqtt
    - auth
